language: android
sudo: false
jdk:
  - oraclejdk8

android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra

script:
  - ./gradlew build # by default it is build connectedCheck

after_success:
  - cat ./app/build/reports/lint-results.html
  - ./gradlew clean jacocoTestReport coveralls
