language: android
sudo: false
jdk:
  - oraclejdk8

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

script:
  - ./gradlew build # by default it is build connectedCheck

after_success:
  - cat app/build/outputs/lint-results-debug.html
  - ./gradlew clean jacocoTestReport coveralls
