language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra

script:
  - ./gradlew build # by default it is build connectedCheck

after_success:
  - cat app/build/outputs/lint-results-debug.html
  - ./gradlew clean jacocoTestReport
  - mkdir -p build/reports/jacoco/test
  - cp build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml build/reports/jacoco/test/
  - ./gradlew coveralls
